### ISSUE TITLE
Plain JavaScript templates with `.js` extension don't seem to be working with v4.0

### ISSUE THREAD

**Issue by saneef** [asciidoctor/asciidoctor.js#1841]
**Describe the bug**
Plain JS templates with `.js` extensions are not applied.

**To Reproduce**
I have created a test repo: [saneef/testing-js-templates-asciidoctor-js-4](https://github.com/saneef/testing-js-templates-asciidoctor-js-4)
There are two branches with:

1. **[main](https://github.com/saneef/testing-js-templates-asciidoctor-js-4):** Package is marked `"type": "module"` and code is written in ESM. 
2. **[commonjs](https://github.com/saneef/testing-js-templates-asciidoctor-js-4/tree/commonjs):** All code is written in commonjs.

In the ESM, if you run `node index.js`, you will see:

```bash
❯ node index.js
file:///Users/saneef/tmp/tmp_tmp/asciidoctor-4/node_modules/@asciidoctor/core/src/converter/template.js:160
    const result = template.render({ node: proxyNode, opts, helpers })
                            ^

TypeError: template.render is not a function
    at TemplateConverter.convert (file:///Users/saneef/tmp/tmp_tmp/asciidoctor-4/node_modules/@asciidoctor/core/src/converter/template.js:160:29)
    at async Document.content (file:///Users/saneef/tmp/tmp_tmp/asciidoctor-4/node_modules/@asciidoctor/core/src/abstract_block.js:266:47)
    at async Html5Converter.convert_embedded (file:///Users/saneef/tmp/tmp_tmp/asciidoctor-4/node_modules/@asciidoctor/core/src/converter/html5.js:448:17)
    at async Document.convert (file:///Users/saneef/tmp/tmp_tmp/asciidoctor-4/node_modules/@asciidoctor/core/src/document.js:1064:16)
    at async convert (file:///Users/saneef/tmp/tmp_tmp/asciidoctor-4/node_modules/@asciidoctor/core/src/convert.js:197:14)
    at async file:///Users/saneef/tmp/tmp_tmp/asciidoctor-4/index.js:6:14

Node.js v24.15.0
```

In commonjs, if you run `node index.js`, no error but the template is not applied.

**Expected behavior**
The template should be applied, should see this output:

```bash
❯ node index.js
<div class="listingblock">
<div class="content">
<pre class="highlight"><code class="language-ruby" data-lang="ruby">puts "Hello, World!"</code></pre>
</div>
</div>
```

**Versions**
 - OS: macOS 26.5.1
 - Node 24.15.0
 - Asciidoctor.js version: 4.0.0

**Additional context**
Surprisingly, if I rename `listing.js` to `listing.mjs` it works fine, above two code variations. Even if code written in `listing.mjs` ESM or commonjs, it works.

**Comment by ggrossetie** [comment]
Thanks for the detailed report!
Here's what's actually happening:

- **`.mjs` only *appears* to work.** `.mjs` isn't in the list of recognized template extensions, so the file is silently skipped, no custom converter is registered, and Asciidoctor falls back to the built-in HTML5 converter. The output looks reasonable but your template is never applied.
- **`.js` in an ESM project throws `template.render is not a function`** because templates are loaded with `createRequire(import.meta.url)`. When a `.js` file is resolved as ESM, that call returns the module namespace object instead of your render function.
- Your project's `package.json` (`"type"`) doesn't change any of this on our side: Asciidoctor.js never reads it. It only affects how Node itself evaluates a `.js` file.

The fix: `.js` and `.mjs` templates (and the optional `helpers` file) are now loaded with a dynamic `import()` and the render function is taken from the module's default export, with `.mjs` added to the recognized extensions. All combinations of `.js` / `.cjs` / `.mjs` × ESM / CJS should now apply the template correctly.

**Comment by saneef** [comment]
Thank you @ggrossetie!

> * **`.mjs` only _appears_ to work.** `.mjs` isn't in the list of recognised template extensions, so the file is silently skipped...

🤦 My bad! Didn't realise wrong thing is getting printed. 

I'm glad you figured it out.
