### ISSUE TITLE
Error after upgrading to 2.1.0

### ISSUE THREAD

**Issue by thorstenkampe** [asciidoctor/asciidoctor.js#846]
This is on Windows with node v13.9.0:
```
F:\PortableApps\SDK\nodejs\node_modules\asciidoctor\bin\asciidoctor:7
cli.run(process.argv)
    ^

TypeError: undefined is not a function
    at Object.<anonymous> (F:\PortableApps\SDK\nodejs\node_modules\asciidoctor\bin\asciidoctor:7:5)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by Mogztter** [comment]
Hello @thorstenkampe 

I can reproduce this issue on Windows (I didn't try on Linux yet) using Node `v12.13.0` and npm `6.12.0`.
I'm not sure why but the dependency `@asciidoctor/cli` is not fetched... As you can see on the package.json and on npmjs the dependency is present: https://www.npmjs.com/package/asciidoctor but my `node_modules` only contains `@asciidoctor/core`:

```console
> ls .\node_modules\@asciidoctor\


    Répertoire : C:\Users\guillaume\test\node_modules\@asciidoctor


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       25/02/2020     21:33                core

```

Here's an extract from my `package-lock.json`:

```json
"asciidoctor": {
  "version": "2.1.1",
   "resolved": "https://registry.npmjs.org/asciidoctor/-/asciidoctor-2.1.1.tgz",
   "integrity": "sha512-YfgnQ/dudXm1klwZTV0OXFoX+wl17amJSFlFLNROSBjyVaT04uq+9gwZ84nCUy5sr5UrBqS+Q7ZFYssFoLqYkQ==",
   "requires": {
     "@asciidoctor/cli": "3.2.0",
     "@asciidoctor/core": "2.1.1"
   },
   "dependencies": {
     "@asciidoctor/cli": {
       "version": "3.2.0",
       "resolved": "https://registry.npmjs.org/@asciidoctor/cli/-/cli-3.2.0.tgz",
       "integrity": "sha512-AEy8hJLE5BuCWaIzZZ+lXv1tgBq0zNF0G/mfImKYIF36vwLJkck/5A/F4mcA8HwXh0/cjKUgfiWLwDVAfDPoWw==",
       "requires": {
         "yargs": "13.2.2"
       }
     }
   }
 }
```

If I force install `npm i @asciidoctor/cli` then it's working... is that a npm bug? Am I missing something?

**Comment by Mogztter** [comment]
The `@asciidoctor/cli` package is actually installed in the `asciidoctor` package:

https://blog.npmjs.org/post/189618601100/binary-planting-with-the-npm-cli

```
.\node_modules\asciidoctor\node_modules\@asciidoctor\cli
```

And if you run the CLI from there, it's also working:
```console
> .\node_modules\asciidoctor\node_modules\.bin\asciidoctor.cmd -v
Asciidoctor.js 2.1.1 (Asciidoctor 2.0.10) [https://asciidoctor.org]
Runtime Environment (node v12.13.0 on win32)
CLI version 3.2.0
```

I wonder if it's related to https://blog.npmjs.org/post/189618601100/binary-planting-with-the-npm-cli because `@asciidoctor/cli` and `asciidoctor` package both define the same `bin` path.

**Comment by Mogztter** [comment]
Actually it's my mistake, the API changed and I didn't update the code accordingly... :man_facepalming:
I thought it was a npm issue but no... :sweat_smile:
